### ISSUE TITLE
Source maps have null sourcesContent when ts files spread across folders

### ISSUE THREAD

**Issue by adwilson** [ivogabe/gulp-typescript#256]
I've been having an issue with generating source maps when combining gulp-typescript and gulp-sourcemaps when .ts files are spread across different folders. I cannot be entirely sure if this is a gulp-typescript issue or a gulp-sourcemaps issue but I've had no issues when using, say, gulp-less with .less files spread in different folders.

*Basically, when the .ts files are spread across folders I find that the sourcesContent property of the source map is always null.*

I have an example repo at https://github.com/adwilson/gulp-typescript-sourcemap-issue which has two gulp comnmands "works" and "doesntwork". Both produce a .js file and a .js.map file.

The output of using the "works" gulp command produces...

```
{"version":3,"sources":["first.ts","second.ts"],"names":[],"mappings":"AACA,CAAC;IAEG,IAAI,CAAC,GAAG,CAAC,CAAC;AAEd,CAAC,CAAC,EAAE,CAAC;ACJL,CAAC;IAEG,IAAI,CAAC,GAAG,CAAC,CAAC;AAEd,CAAC,CAAC,CAAA","file":"works.js","sourcesContent":["\r\n(() => {\r\n    \r\n    var a = 1;\r\n    \r\n})();","\r\n(() => {\r\n    \r\n    var b = 2;\r\n    \r\n})"],"sourceRoot":"/source/"}
```
In this command the .ts files are in the same folder together and sourcesContent contains the contents of both files.

Running the other command "doesntwork" produces the following...
```
{"version":3,"sources":["Folder1/first.ts","Folder2/second.ts"],"names":[],"mappings":"AACA,CAAC;IAEG,IAAI,CAAC,GAAG,CAAC,CAAC;AAEd,CAAC,CAAC,EAAE,CAAC;ACJL,CAAC;IAEG,IAAI,CAAC,GAAG,CAAC,CAAC;AAEd,CAAC,CAAC,CAAA","file":"doesntwork.js","sourcesContent":[null,null],"sourceRoot":"/source/"}
```
In this command the .ts files are in different folders, sourcesContent is null for both files.

Apologies if I've misunderstood something basic here and thanks in advance.

**Comment by ivogabe** [comment]
Thanks for reporting, I'll investigate this with your repo.

**Comment by aleung** [comment]
Blocked by the same issue. Is there any update?

**Comment by aleung** [comment]
I workaround this issue by providing `sourceRoot` option to gulp_sourcemaps `write` function:

``` js
  const result = gulp.src([src/**/*.ts, test/**/*.ts])
    .pipe(sourcemaps.init())
    .pipe(typescript(tsconfig));
  const jsStream = result.js
    .pipe(sourcemaps.write('.', {sourceRoot: './', debug: true}))
    .pipe(gulp.dest('./build'));
  const dtsStream = result.dts.pipe(gulp.dest('./build'));
  return merge(jsStream, dtsStream);
```

gulp-sourcemaps loads source from file. The log shows:

```
gulp-sourcemap-write: No source content for "src/model.ts". Loading from file.
```

**Comment by ivogabe** [comment]
@aleung No, I haven't had time to work on this. I will accept a PR if someone else can fix this.

**Comment by willfrew** [comment]
@aleung Thanks, your workaround did the job for me.

**Comment by icholy** [comment]
@aleung Thanks, that fixed it. I've been pulling my hair out for a few hours now ...

**Comment by ivogabe** [comment]
This should be fixed in version 3.0, since the logic that handles the relative paths in source maps has been rewritten. The difficulty was that all paths were relative, but relative to different paths.

**Comment by MisterGoodcat** [comment]
I'm still seeing this issue with version 3.1.3. Source map contents of top-level files are included, but for each and every file located in a sub folder, the generated source map only contains "null" entries for the content.

Any idea?
