### ISSUE TITLE
Could not find input file .../________________empty.ts. This is probably an issue of gulp-typescript.

### ISSUE THREAD

**Issue by monoflash** [ivogabe/gulp-typescript#342]
[21:57:35] Starting 'build.dev'...
[21:57:35] Starting 'build.assets.dev'...
[21:57:35] Finished 'build.assets.dev' after 57 ms
[21:57:35] Starting 'build.html_css'...
[21:57:36] Finished 'build.html_css' after 385 ms
[21:57:36] Starting 'build.js.dev'...
Could not find input file /Users/user/Projects/company/www.domain.com/assets/________________empty.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information: 
sourceRoot = ".../"
sources = ["________________empty.ts"]
[21:57:36] Finished 'build.js.dev' after 38 ms
[21:57:36] Starting 'build.index.dev'...
[21:57:36] gulp-inject 4 files into index.html.
[21:57:36] gulp-inject 2 files into index.html.
[21:57:36] gulp-inject 12 files into index.html.
[21:57:36] Finished 'build.index.dev' after 32 ms
[21:57:36] Finished 'build.dev' after 514 ms

**Your gulpfile:**
```
// --------------
// Build dev watch.
gulp.task('build.dev.watch', (done: any) =>
  runSequence('build.dev',
              'watch.dev',
              done));

```

**tsconfig.json**
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true
  },
  "exclude": [
    "node_modules",
    "dist",
    "typings/browser.d.ts",
    "typings/browser",
    "src"
  ],
  "compileOnSave": false
}

```
Project based on https://github.com/mgechev/angular2-seed
run: npm run build.dev.watch
Periodically take off an error message

**Comment by ivogabe** [comment]
Can you post the gulp task that compiles typescript?

**Comment by ivogabe** [comment]
Or could you create a minimal example that reproduces this, and upload the .zip here on GitHub? That would make it a lot easier for me to debug this.

**Comment by monoflash** [comment]
Unfortunately, this error occurs only when the project is large and I have not yet figured out how it guaranteed to repeat.
All scripts here: https://github.com/mgechev/angular2-seed
All scripts have not changed, only the written components, html templates and css

**Comment by ivogabe** [comment]
I tried the repository that you linked, but that doesn't show the error. So what must I change to make it fail? You may also mail your full project privately to me.

**Comment by GiedriusGrabauskas** [comment]
Same here, with large project.

### Console:
```
cmd.exe /c gulp -b "D:\Projects\Web" --color --gulpfile "D:\Projects\Web\Gulpfile.js" default
(node:14024) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[19:00:31] Using gulpfile D:\Projects\Web\Gulpfile.js
[19:00:31] Starting 'default'...
INFO: Server started at 127.0.0.1:3000
INFO: Started watching files in 'src' folder.
[19:00:32] Finished 'default' after 504 ms
INFO: src\app\actions\accounts\accounts-actions.ts: changed, running tasks...
[19:00:45] Starting '_ts'...
[19:00:54] Starting '_live-reload'...
[19:00:54] Finished '_live-reload' after 5.48 ms
[19:00:54] Finished '_ts' after 9.57 s
INFO: src\app\actions\accounts\accounts-actions-creators.ts: changed, running tasks...
[19:03:39] Starting '_ts'...
Could not find input file D:\Projects\Web\src\app\________________empty.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information: 
sourceRoot = "D:/Projects/Web/src/app/"
sources = ["________________empty.ts"]
[19:03:41] Starting '_live-reload'...
[19:03:41] Finished '_live-reload' after 5.4 ms
[19:03:41] Finished '_ts' after 1.93 s
INFO: src\app\actions\accounts\accounts-actions-creators.ts: changed, running tasks...
[19:04:16] Starting '_ts'...
[19:04:22] Starting '_live-reload'...
[19:04:22] Finished '_live-reload' after 3.64 ms
[19:04:22] Finished '_ts' after 5.7 s
```

### Dependencies:
```json
"devDependencies": {
  "connect-livereload": "0.5.4",
  "del": "2.2.0",
  "express": "4.13.4",
  "gulp": "3.9.1",
  "gulp-autoprefixer": "3.1.0",
  "gulp-replace": "0.5.4",
  "gulp-sass": "2.3.1",
  "gulp-sourcemaps": "1.6.0",
  "gulp-typescript": "2.13.4",
  "gulp-uglify": "1.5.3",
  "jspm": "0.16.34",
  "path": "0.12.7",
  "replace-ext": "0.0.1",
  "tiny-lr": "0.2.1",
  "tsconfig-glob": "0.4.3",
  "tsd": "0.6.5",  
  "typescript": "1.8.10"
}
```

### Typescript configuration:
```js
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": true,
        "preserveConstEnums": true,
        "removeComments": false,
        "sourceMap": true,
        "inlineSources": true,
        "noExternalResolve": true,
        "jsx": "react"
    },
    "filesGlob": [
        "./src/**/*.ts*"
    ],
    "files": [ 
      /* 251 files list */
    ]
}
```

**Comment by ivogabe** [comment]
Could you upload your full project as a zip here?

**Comment by diestrin** [comment]
Same here. Big project and can't upload it or find a way to reproduce it.
Only thing is that if I run the gulp-typescript directly it doesn't happen (to me) but it does happen when coming form a watch task, after the first iteration. :/

```
[17:59:46] Starting 'tsc-app'...
[17:59:46] Typescript Changed node_modules/angular2/typings/browser.d.ts
[17:59:47] Typescript Changed 1 item
Could not find input file /Volumes/HHD/Projects/18Techs/Weather/twc_cms_wu/docroot/sites/all/modules/wu/node_modules/angular2/typings/________________empty.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "/Volumes/HHD/Projects/18Techs/Weather/twc_cms_wu/docroot/sites/all/modules/wu/node_modules/angular2/typings/"
sources = ["________________empty.ts"]
[17:59:47] Finished 'tsc-app' after 441 ms
[17:59:47] Starting 'tsc'...
[17:59:47] Typescript Changed node_modules/angular2/typings/browser.d.ts
[17:59:47] Typescript Changed src/settings.ts
/Volumes/HHD/Projects/18Techs/Weather/twc_cms_wu/docroot/sites/all/modules/wu/src/________________empty.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "/Volumes/HHD/Projects/18Techs/Weather/twc_cms_wu/docroot/sites/all/modules/wu/src/"
sources = ["________________empty.ts"]
[17:59:48] TypeScript: emit succeeded
```

**Comment by ivogabe** [comment]
@diestrin is there something special with your watch tasj? Do you use gulp-changed or something like that?

**Comment by GiedriusGrabauskas** [comment]
Using simplr-gulp: https://github.com/QuatroCode/simplr-gulp/tree/dev
[test-fails.zip](https://github.com/ivogabe/gulp-typescript/files/262867/tests.zip)
Error coming from watch task. (`gulp default`).

**Comment by diestrin** [comment]
Yes @ivogabe. I was trying to debug it but couldn't get to the root problem. This is my gulp task
```
function compileTS(src, dest, project, onlyChanged) {
  return gulp.src([
    'node_modules/angular2/typings/browser.d.ts',
    `${src}/**/**.ts`,
    `!${appSrc}/node_modules/**/*`
  ])
  .pipe(gulpif(!!onlyChanged, changed(src, { extension: '.js' })))
  .pipe(gulpif(!!onlyChanged, debug({title: 'Typescript Changed'})))
  .pipe(sourcemaps.init())
  .pipe(ts(project))
  .pipe(sourcemaps.write('.', {
    includeContent: false
  }))
  .pipe(gulp.dest(dest + '/src'))
  .pipe(ignore('*.js.map'))
  .pipe(ignore('*.spec.js'))
  .pipe(renameExtension('.min.js'))
  .pipe(minifyJS(uglifyOptions))
  .pipe(gulp.dest(dest + '/src'));
}
```

**Comment by ivogabe** [comment]
I think it's the same issue as https://github.com/ivogabe/gulp-typescript/issues/307#issuecomment-218995719. Does it only show the error when a new compilation is triggered, but no files were changed? If so, then it is probably the same.

**Comment by diestrin** [comment]
mmm just tested and it happens on both, when there's changes and when there's no changes

**Comment by DiegoYungh** [comment]
Same was happening here on angular2-seed project.

I refreshed my tools:

`sudo npm i ts-node -g`
and
`typings install`

I suppose it is something wrong in the file list returned by the glob, somewhere in the results list there is an item "________________empty", might be some left overs from typings.

Just happen to see all problems listed here related to typings/tsd

if nothing works try to wipe your typings folder and install it again and give some feedback, mine was solved with the commands above only...

**Comment by thomas-darling** [comment]
Same problem here in an large Aurelia project.
Looks like it happens the first time a file change is detected by the watch task.

**Comment by zachallen** [comment]
I can reproduce it by using the [angular2-seed project](https://github.com/mgechev/angular2-seed). If you change an arbitrary file (app.component.html) and it happens on the second change/live-reload. I reverted back to version 2.12.1 and the issue no longer happens.

**Comment by brijeshamin** [comment]
Still able to reproduce this issue on my project which is based on angular2-seed.
My project is using,  "gulp-typescript": "2.13.4"

**Comment by pe8ter** [comment]
@brijeshamin The bug is fixed, but hasn't been released through npm yet.

**Comment by ivogabe** [comment]
The fix was released in [v2.13.5](https://github.com/ivogabe/gulp-typescript/releases/tag/v2.13.5)

**Comment by sondreb** [comment]
I'm still seeing this once in a while on watch recompiles. Using latest version 2.13.6. Hard to reproduce, it only happens once in a while when editing files. Normally I discover it when logic does not change in the app, but often I end up doing many changes before I realize it's the gulp build process that have failed.

**Comment by ivogabe** [comment]
I'm afraid that I can't fix it without some more info.. Could you debug it? Or post your gulpfile and tsconfig?

**Comment by GeorgeTaveras1231** [comment]
I was experiencing this same issue and found a solution that seems to work (I have triggered multiple `watch` re-compiles and they have been stable).

The problem seems to be that I was re-using the `tsProject` object across recompiles. I was able to fix it by forcing my `compile` task to re-create that object each time.

### My original configurations

`gulpfile.js`
```javascript
const gulp = require('gulp');
const ts = require('gulp-typescript');

// PROBLEM: defined at top-level and re-used across watch recompiles
const tsProject = ts.createProject('tsconfig.json'); 

gulp.task('compile', () => {
      const tsResult = gulp
      .src([ /** CODE_FILES, TYPINGS_FILE **/ ])
      .pipe(ts(tsProject));

    return tsResult.js.pipe(gulp.dest('compiled/src'));
});

gulp.task('watch', () => {
  gulp.watch([ /** files **/], [ 'compile' ])
})
```

### Fix
`gulpfile.js`
```javascript
const gulp = require('gulp');
const ts = require('gulp-typescript');

gulp.task('compile', () => {
   // Fix: Recreate tsProject per compile;
   const tsProject = ts.createProject('tsconfig.json');
    const tsResult = gulp
      .src([ /** CODE_FILES, TYPINGS_FILE **/ ])
      .pipe(ts(tsProject));

    return tsResult.js.pipe(gulp.dest('compiled/src'));
});

gulp.task('watch', () => {
  gulp.watch([ /** files **/], [ 'compile' ])
})
```

**Comment by mko** [comment]
I've run into this problem myself on `gulp-typescript@2.13.6` on a larger project developing an Angular 2 components library where there's two separate TSProjects with two separate build tasks and two separate watch tasks (component library itself and the demo application consuming the component library). Using the `mgechev/angular2-seed` as a base, I found that the problem seems to be solved in the complex seed project by forcing the `tsProject` file to be not cached by `contra/gulp-cached` and (similar to @GeorgeTaveras1231's solution above) moving the `tsProject` definition into a constant inside of the task itself so it gets recreated every time `gulp-watch` runs the originally defined `gulp-typescript` task.

The bigger issue that I'd like to understand is why re-using the TSProject is a problem with incremental compilation. This issue is clearly separate from the one fixed in `2.13.5`, as this is a problem specifically *when* files are changed, but it may be actually working as intended and not even be a bug.

**Comment by ivogabe** [comment]
I don't know yet when this error occurs since I haven't got a reproduction for this. I already fixed it in other situations, so I'd like to see your project code to debug it. Could you send it here or by email, or create some example project that reproduces it? Moving `tsProject` into the task function is not the real solution since that breaks incremental compilation. I do advise to not use `gulp-cached` since unchanged files must also be recompiled. Type info from one file can modify the output of other files and affects type checking of other files.

**Comment by mko** [comment]
Realistically, I can't easily provide a repro of it due to time constraints and confidentiality of the files in question, but the general gist would be:

1. Make a copy of `mgechev/angular2-seed`
2. Implement a second build and watch step for a different set of files from the core application files.
3. Run watchers and see the build fail at the `gulp-typescript` step.

If I get time this week, I'll try to create a demo repo that has the same issue.

**Comment by ivogabe** [comment]
I'll see if I have some time to check that. A quick question, is the same tsProject used in two compilations at the same time? And is the error shown for `________________empty.ts` only, or for other files?
Is the contents of `tools` confidential too? If not, you might could replace the contents of `src` of your project with some placeholder code and that will probably demonstrate the same issue.

**Comment by GiedriusGrabauskas** [comment]
Okey, now I get this error from build task.

[gulp-typescript-empty-error.zip](https://github.com/ivogabe/gulp-typescript/files/412317/gulp-typescript-empty-error.zip)

1) Run `npm install`
2) Start default command: `gulp`.

And `not-working` task will show you a error message:
```
Could not find input file D:\test\src\start.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "D:/test/src/"
sources = ["start.ts"]
Could not find input file D:\test\src\________________empty.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "D:/test/src/"
sources = ["________________empty.ts"]
```
Difference between `working` and `not-working` tasks are only in `tsconfig.json` file.

**Comment by DovydasNavickas** [comment]
@GiedriusGrabauskas I had to add `'use strict';` at the top of `gulpfile.js`, but apart from that - that's a working repro. Good job!
@ivogabe could you take a look at that one? We already have a repro, which will make it way easier to solve the bug.

**Comment by PWKad** [comment]
Not sure how helpful this comment is but I had a project that had multiple TypeScript projects being created and running concurrently.  I had a glob pattern set to `typings/**/*.d.ts` in `gulp.src` and it was giving me this error.  I removed that pattern and moved it to the `tsconfig.json` and it's running fine now.

**Comment by PWKad** [comment]
Ah I think I found it it seems to be due to `index.d.ts` being empty and only having comments like this - 

```
/// <reference path="globals/angular-protractor/index.d.ts" />
```

**Comment by jwbuitenhuis** [comment]
+1

**Comment by ivogabe** [comment]
This should not happen any more in version 3, since `____empty.ts` is not passed to the compiler any more. This file is not needed any more now that `rootDir` is always set. See #413 for more details on version 3.
